
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQAbstractGraphicsShapeItempen(void * obj);
EXTERNC void QWQAbstractGraphicsShapeItemsetPen(void * obj, void * pen);
EXTERNC void * QWQAbstractGraphicsShapeItembrush(void * obj);
EXTERNC void QWQAbstractGraphicsShapeItemsetBrush(void * obj, void * brush);
