
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include "QActionGroup.hpp"

void * QWQActionGroupCtor(void * parent)
{
    QObject * xparent = reinterpret_cast<QObject *>(parent);
    QActionGroup * ptr = new QActionGroup(xparent);
    return reinterpret_cast<void *>(ptr);
}

void * SCWQActionGroupCtor(void * parent)
{
    QObject * xparent = reinterpret_cast<QObject *>(parent);
    SCQActionGroup * ptr = new SCQActionGroup(xparent);
    return reinterpret_cast<void *>(ptr);
}

void * QWQActionGroupaddAction_1(void * obj, void * a)
{
    QActionGroup * ptr = reinterpret_cast<QActionGroup *>(obj);
    QAction * xa = reinterpret_cast<QAction *>(a);
    QAction * retVal = ptr->addAction(xa);
    return retVal;
}

void QWvalidateCB_QActionGroup(void *obj, int32_t objId, char *methodName)
{
    SCQActionGroup * ptr = reinterpret_cast<SCQActionGroup *>(obj);

    ptr->validateEvent(objId, methodName);

}
void QWQActionGroupDtor(void * obj)
{
    QActionGroup * ptr = reinterpret_cast<QActionGroup *>(obj);
    delete ptr;
}

void SCWQActionGroupDtor(void * obj)
{
    QActionGroup * ptr = reinterpret_cast<QActionGroup *>(obj);
    delete ptr;
}

