
// 
// This file has been automatically generated by RaQt_maker V0.0.2.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQActionCtor_1(void * parent);
EXTERNC void  QWQActiontrigger(void * obj);
EXTERNC void  QWQActionsetEnabled(void * obj, int8_t  arg1);
EXTERNC void  QWQActionsetDisabled(void * obj, int8_t  b);
EXTERNC void QWQActionDtor(void *);
