
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void QWQBoxLayoutaddLayout(void * obj, void * layout, int32_t  stretch);
EXTERNC int32_t QWQBoxLayoutspacing(void * obj);
EXTERNC void QWQBoxLayoutsetSpacing(void * obj, int32_t  spacing);
EXTERNC int8_t QWQBoxLayoutsetStretchFactor_1(void * obj, void * w, int32_t  stretch);
EXTERNC int8_t QWQBoxLayoutsetStretchFactor_2(void * obj, void * l, int32_t  stretch);
EXTERNC void QWQBoxLayoutsetStretch(void * obj, int32_t  index, int32_t  stretch);
EXTERNC int32_t QWQBoxLayoutstretch(void * obj, int32_t  index);
