
// 
// This file has been automatically generated by RaQt_maker V0.0.2.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QBoxLayout.h"

void QWQBoxLayoutaddLayout(void * obj, void * layout, int32_t  stretch)
{
    QBoxLayout * ptr = reinterpret_cast<QBoxLayout *>(obj);
    QLayout * xlayout = reinterpret_cast<QLayout *>(layout);
    int xstretch = stretch;
    ptr->addLayout(xlayout, xstretch);
}

