
// 
// This file has been automatically generated by RaQt_maker V0.0.4.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC int8_t QWQCoreApplicationsendEvent(void * receiver, void * event);
EXTERNC void QWQCoreApplicationquit();
