
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QEvent.h"
#include "QtWidgetsWrapper.hpp"

class SCQEvent : public QEvent, public CallbackValidator
{
public:
    SCQEvent(Type type):
        QEvent(type)
    { }

    SCQEvent(const QEvent& other):
        QEvent(other)
    { }

    ~SCQEvent() { }

};

