
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"


EXTERNC void  QWQFileDialoggetOpenFileName(
                    void * retBuffer,
                    void * parent,
                    char * caption,
                    char * dir, 
                    char * filter,
                    void * sfBuffer,
                    int32_t  options);


EXTERNC void  QWQFileDialoggetSaveFileName(
                    void * retBuffer,
                    void * parent,
                    char * caption,
                    char * dir, 
                    char * filter,
                    void * sfBuffer,
                    int32_t  options);

