
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QGraphicsItem.h"
#include "QtWidgetsWrapper.hpp"

class SCQGraphicsItem : public QGraphicsItem, public CallbackValidator
{
public:
    ~SCQGraphicsItem() { }

    bool contains(const QPointF& point) const
    {
        if (m_contains) {
            return (*callbackQPointFReturnsBool)(
                m_objId, "contains",
                point
            );
        } else {
            return QGraphicsItem::contains(point);
        }
    }

};

