
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include "QGraphicsLineItem.hpp"

void * QWQGraphicsLineItemCtor_3(double  x1, double  y1, double  x2, double  y2, void * parent)
{
    qreal xx1 = x1;
    qreal xy1 = y1;
    qreal xx2 = x2;
    qreal xy2 = y2;
    QGraphicsItem * xparent = reinterpret_cast<QGraphicsItem *>(parent);
    QGraphicsLineItem * ptr = new QGraphicsLineItem(xx1, xy1, xx2, xy2, xparent);
    return reinterpret_cast<void *>(ptr);
}

void * SCWQGraphicsLineItemCtor_3(double  x1, double  y1, double  x2, double  y2, void * parent)
{
    qreal xx1 = x1;
    qreal xy1 = y1;
    qreal xx2 = x2;
    qreal xy2 = y2;
    QGraphicsItem * xparent = reinterpret_cast<QGraphicsItem *>(parent);
    SCQGraphicsLineItem * ptr = new SCQGraphicsLineItem(xx1, xy1, xx2, xy2, xparent);
    return reinterpret_cast<void *>(ptr);
}

void QWQGraphicsLineItemsetPen(void * obj, void * pen)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    QPen & xpen = * reinterpret_cast<QPen *>(pen);
    ptr->setPen(xpen);
}

void QWQGraphicsLineItemsetLine_2(void * obj, double  x1, double  y1, double  x2, double  y2)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    qreal xx1 = x1;
    qreal xy1 = y1;
    qreal xx2 = x2;
    qreal xy2 = y2;
    ptr->setLine(xx1, xy1, xx2, xy2);
}

void * QWQGraphicsLineItemboundingRect(void * obj)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    QRectF retVal = ptr->boundingRect();
    QRectF * xxretVal = new QRectF(retVal);
    void * xretVal = reinterpret_cast<void *>(xxretVal);
    return xretVal;
}

int8_t QWQGraphicsLineItemcontains(void * obj, void * point)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    QPointF & xpoint = * reinterpret_cast<QPointF *>(point);
    bool retVal = ptr->contains(xpoint);
    return retVal;
}

void QWvalidateCB_QGraphicsLineItem(void *obj, int32_t objId, char *methodName)
{
    SCQGraphicsLineItem * ptr = reinterpret_cast<SCQGraphicsLineItem *>(obj);

    ptr->validateEvent(objId, methodName);

}
void QWQGraphicsLineItemDtor(void * obj)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    delete ptr;
}

void SCWQGraphicsLineItemDtor(void * obj)
{
    QGraphicsLineItem * ptr = reinterpret_cast<QGraphicsLineItem *>(obj);
    delete ptr;
}

