
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQHBoxLayoutCtor_1();
EXTERNC void * SCWQHBoxLayoutCtor_1();
EXTERNC void QWvalidateCB_QHBoxLayout(void *obj, int32_t objId, char *methodName);
EXTERNC void QWQHBoxLayoutDtor(void *);
EXTERNC void SCWQHBoxLayoutDtor(void *);
