
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQImageCtor_3(int32_t  width, int32_t  height, int  format);
EXTERNC void * SCWQImageCtor_3(int32_t  width, int32_t  height, int  format);
EXTERNC int32_t QWQImagewidth(void * obj);
EXTERNC int32_t QWQImageheight(void * obj);
EXTERNC void * QWQImagepixelColor_1(void * obj, int32_t  x, int32_t  y);
EXTERNC void QWQImagefill_2(void * obj, void * color);
EXTERNC void QWvalidateCB_QImage(void *obj, int32_t objId, char *methodName);
EXTERNC void QWQImageDtor(void *);
EXTERNC void SCWQImageDtor(void *);
