
// 
// This file has been automatically generated by RaQt_maker V0.0.5.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QMessageBox.h"
#include "QtWidgetsWrapper.hpp"

class SCQMessageBox : public QMessageBox, public CallbackValidator
{
public:
    SCQMessageBox(QWidget* parent):
        QMessageBox(parent)
    { }

    ~SCQMessageBox() { }

    void closeEvent(QCloseEvent* event)
    {
        if (m_closeEvent) {
            (*slotCallbackQCloseEvent)(
                m_objId, "closeEvent",
                event
            );
        } else {
            QMessageBox::closeEvent(event);
        }
    }

    void enterEvent(QEvent* event)
    {
        if (m_enterEvent) {
            (*slotCallbackQEvent)(
                m_objId, "enterEvent",
                event
            );
        } else {
            QMessageBox::enterEvent(event);
        }
    }

    void leaveEvent(QEvent* event)
    {
        if (m_leaveEvent) {
            (*slotCallbackQEvent)(
                m_objId, "leaveEvent",
                event
            );
        } else {
            QMessageBox::leaveEvent(event);
        }
    }

    void mouseMoveEvent(QMouseEvent* event)
    {
        if (m_mouseMoveEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mouseMoveEvent",
                event
            );
        } else {
            QMessageBox::mouseMoveEvent(event);
        }
    }

    void mousePressEvent(QMouseEvent* event)
    {
        if (m_mousePressEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mousePressEvent",
                event
            );
        } else {
            QMessageBox::mousePressEvent(event);
        }
    }

    void mouseReleaseEvent(QMouseEvent* event)
    {
        if (m_mouseReleaseEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mouseReleaseEvent",
                event
            );
        } else {
            QMessageBox::mouseReleaseEvent(event);
        }
    }

    void paintEvent(QPaintEvent* event)
    {
        if (m_paintEvent) {
            (*slotCallbackQPaintEvent)(
                m_objId, "paintEvent",
                event
            );
        } else {
            QMessageBox::paintEvent(event);
        }
    }

    void resizeEvent(QResizeEvent* event)
    {
        if (m_resizeEvent) {
            (*slotCallbackQResizeEvent)(
                m_objId, "resizeEvent",
                event
            );
        } else {
            QMessageBox::resizeEvent(event);
        }
    }

};

