
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QMouseEvent.h"
#include "QtWidgetsWrapper.hpp"

class SCQMouseEvent : public QMouseEvent, public CallbackValidator
{
public:
    SCQMouseEvent(Type type, const QPointF& localPos, Qt::MouseButton button, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers):
        QMouseEvent(type, localPos, button, buttons, modifiers)
    { }

    SCQMouseEvent(Type type, const QPointF& localPos, const QPointF& screenPos, Qt::MouseButton button, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers):
        QMouseEvent(type, localPos, screenPos, button, buttons, modifiers)
    { }

    SCQMouseEvent(Type type, const QPointF& localPos, const QPointF& windowPos, const QPointF& screenPos, Qt::MouseButton button, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers):
        QMouseEvent(type, localPos, windowPos, screenPos, button, buttons, modifiers)
    { }

    SCQMouseEvent(Type type, const QPointF& localPos, const QPointF& windowPos, const QPointF& screenPos, Qt::MouseButton button, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::MouseEventSource source):
        QMouseEvent(type, localPos, windowPos, screenPos, button, buttons, modifiers, source)
    { }

    ~SCQMouseEvent() { }

};

