
// 
// This file has been automatically generated by RaQt_maker V0.0.5.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQRadioButtonCtor_1(void * parent);
EXTERNC void * SCWQRadioButtonCtor_1(void * parent);
EXTERNC void * QWQRadioButtonCtor_2(char * text, void * parent);
EXTERNC void * SCWQRadioButtonCtor_2(char * text, void * parent);
EXTERNC void QWvalidateCB_QRadioButton(void *obj, int32_t objId, char *methodName);
EXTERNC void QWQRadioButtonDtor(void *);
EXTERNC void SCWQRadioButtonDtor(void *);
