
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QRect.h"
#include "QtWidgetsWrapper.hpp"

class SCQRect : public QRect, public CallbackValidator
{
public:
    SCQRect():
        QRect()
    { }

    SCQRect(const QPoint& topleft, const QPoint& bottomright):
        QRect(topleft, bottomright)
    { }

    SCQRect(int left, int top, int width, int height):
        QRect(left, top, width, height)
    { }

    ~SCQRect() { }

};

