
// 
// This file has been automatically generated by RaQt_maker V0.0.7.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQResizeEventCtor(void * size, void * oldSize);
EXTERNC void * SCWQResizeEventCtor(void * size, void * oldSize);
EXTERNC void * QWQResizeEventsize(void * obj);
EXTERNC void * QWQResizeEventoldSize(void * obj);
EXTERNC void QWvalidateCB_QResizeEvent(void *obj, int32_t objId, char *methodName);
EXTERNC void QWQResizeEventDtor(void *);
EXTERNC void SCWQResizeEventDtor(void *);
