
// 
// This file has been automatically generated by RaQt_maker V0.0.3.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include "QResizeEvent.h"

void * QWQResizeEventCtor(void * size, void * oldSize)
{
    QSize & xsize = * reinterpret_cast<QSize *>(size);
    QSize & xoldSize = * reinterpret_cast<QSize *>(oldSize);
    QResizeEvent * ptr = new QResizeEvent(xsize, xoldSize);
    return reinterpret_cast<void *>(ptr);
}

void * QWQResizeEventsize(void * obj)
{
    QResizeEvent * ptr = reinterpret_cast<QResizeEvent *>(obj);
    const QSize & retVal = ptr->size();
    void * xretVal = const_cast<void *>(reinterpret_cast<const void *>(& retVal));
    return xretVal;
}

void * QWQResizeEventoldSize(void * obj)
{
    QResizeEvent * ptr = reinterpret_cast<QResizeEvent *>(obj);
    const QSize & retVal = ptr->oldSize();
    void * xretVal = const_cast<void *>(reinterpret_cast<const void *>(& retVal));
    return xretVal;
}

void QWQResizeEventDtor(void * obj)
{
    QResizeEvent * ptr = reinterpret_cast<QResizeEvent *>(obj);
    delete ptr;
}

