
// 
// This file has been automatically generated by RaQt_maker V0.0.5.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QTextEdit.h"
#include "QtWidgetsWrapper.hpp"

class SCQTextEdit : public QTextEdit, public CallbackValidator
{
public:
    SCQTextEdit(QWidget* parent):
        QTextEdit(parent)
    { }

    ~SCQTextEdit() { }

    void closeEvent(QCloseEvent* event)
    {
        if (m_closeEvent) {
            (*slotCallbackQCloseEvent)(
                m_objId, "closeEvent",
                event
            );
        } else {
            QTextEdit::closeEvent(event);
        }
    }

    void enterEvent(QEvent* event)
    {
        if (m_enterEvent) {
            (*slotCallbackQEvent)(
                m_objId, "enterEvent",
                event
            );
        } else {
            QTextEdit::enterEvent(event);
        }
    }

    void leaveEvent(QEvent* event)
    {
        if (m_leaveEvent) {
            (*slotCallbackQEvent)(
                m_objId, "leaveEvent",
                event
            );
        } else {
            QTextEdit::leaveEvent(event);
        }
    }

    void mouseMoveEvent(QMouseEvent* event)
    {
        if (m_mouseMoveEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mouseMoveEvent",
                event
            );
        } else {
            QTextEdit::mouseMoveEvent(event);
        }
    }

    void mousePressEvent(QMouseEvent* event)
    {
        if (m_mousePressEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mousePressEvent",
                event
            );
        } else {
            QTextEdit::mousePressEvent(event);
        }
    }

    void mouseReleaseEvent(QMouseEvent* event)
    {
        if (m_mouseReleaseEvent) {
            (*slotCallbackQMouseEvent)(
                m_objId, "mouseReleaseEvent",
                event
            );
        } else {
            QTextEdit::mouseReleaseEvent(event);
        }
    }

    void paintEvent(QPaintEvent* event)
    {
        if (m_paintEvent) {
            (*slotCallbackQPaintEvent)(
                m_objId, "paintEvent",
                event
            );
        } else {
            QTextEdit::paintEvent(event);
        }
    }

    void resizeEvent(QResizeEvent* event)
    {
        if (m_resizeEvent) {
            (*slotCallbackQResizeEvent)(
                m_objId, "resizeEvent",
                event
            );
        } else {
            QTextEdit::resizeEvent(event);
        }
    }

};

