
// 
// This file has been automatically generated by RaQt_maker V0.0.2.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 


#include "QTimer.h"

void * QWQTimerCtor(void * parent)
{
    QObject * xparent = reinterpret_cast<QObject *>(parent);
    QTimer * ptr = new QTimer(xparent);
    return reinterpret_cast<void *>(ptr);
}

void QWQTimersetInterval_1(void * obj, int32_t  msec)
{
    QTimer * ptr = reinterpret_cast<QTimer *>(obj);
    int xmsec = msec;
    ptr->setInterval(xmsec);
}

void QWQTimerstart_2(void * obj)
{
    QTimer * ptr = reinterpret_cast<QTimer *>(obj);
    ptr->start();
}

void QWQTimerstop(void * obj)
{
    QTimer * ptr = reinterpret_cast<QTimer *>(obj);
    ptr->stop();
}

void QWQTimerDtor(void * obj)
{
    QTimer * ptr = reinterpret_cast<QTimer *>(obj);
    delete ptr;
}

