
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 



#include <stdint.h>

#ifdef __cplusplus
#define EXTERNC extern "C"
#else
#define EXTERNC
#endif


// What std size for integers ???
#define STD_INT long



EXTERNC void * QWApplicationCtor(int argc, char **argv);

EXTERNC int QWApplicationExec(void * obj);

EXTERNC void * QWApplicationInstance();


EXTERNC void QWEmit_(void * source, char * signalName);
EXTERNC void QWEmit_Int(void * source, char * signalName, int32_t data);
EXTERNC void QWEmit_Str(void * source, char * signalName, char * data);
EXTERNC void QWEmit_Bool(void * source, char * signalName, int32_t data);



EXTERNC int8_t QWconnect(void * source, char *signal,
                         void * destination, char *slot);

EXTERNC int8_t QWdisconnect(void * source, char *signal,
                            void * destination, char *slot);

EXTERNC void * QWConnectorRCTOR(int32_t objId, char * slotName, char * sigName);

EXTERNC void QWConnectorRDTOR(void * obj);

EXTERNC void * QWConnectorECTOR(int32_t objId, char * slotName, char * sigName);

EXTERNC void QWConnectorEDTOR(void * obj);


///////////////////////////////////////////////////////////////

// Native helpers

EXTERNC char * QWGetStringFromPointer(void * ptr);

EXTERNC void * QWGetPointerFromString(char * str);

EXTERNC double QWGetDoubleFromPointer(void * ptr);

EXTERNC void * QWGetPointerFromDouble(double * pd);

EXTERNC int64_t QWPointer2Int(void * val);

EXTERNC void * QWInt2Pointer(int64_t val);



// Callbacks initializers

EXTERNC void QWSetupSlotCallback(
    void (*f)(int objId, char *slotName));

EXTERNC void QWSetupSlotCallbackInt(
    void (*f)(int objId, char *slotName, STD_INT i));

EXTERNC void QWSetupSlotCallbackInt2(
    void (*f)(int objId, char *slotName, STD_INT i1, STD_INT i2));

EXTERNC void QWSetupSlotCallbackStr(
    void (*f)(int objId, char *slotName, char *s));

EXTERNC void QWSetupSlotCallbackIntStr(
    void (*f)(int objId, char *slotName, STD_INT i, char *s));

EXTERNC void QWSetupSlotCallbackBool(
    void (*f)(int objId, char *slotName, uchar b));

EXTERNC void QWSetupSlotCallbackQSize(
    void (*f)(int objId, char *slotName, void *p));

EXTERNC void QWSetupSlotCallbackPointer(
    void (*f)(int objId, char *slotName, void *p));

EXTERNC void QWSetupcallback(
    void (*f)(int32_t objId, const char *slotName));

EXTERNC void QWSetupcallbackIntReturnsInt(
    int (*f)(int32_t objId, const char *slotName, int arg1));

EXTERNC void QWSetupcallbackQCloseEvent(
    void (*f)(int32_t objId, const char *slotName, QCloseEvent* event));

EXTERNC void QWSetupcallbackQEvent(
    void (*f)(int32_t objId, const char *slotName, QEvent* event));

EXTERNC void QWSetupcallbackQEventReturnsBool(
    bool (*f)(int32_t objId, const char *slotName, QEvent* event));

EXTERNC void QWSetupcallbackQGraphicsSceneMouseEvent(
    void (*f)(int32_t objId, const char *slotName, QGraphicsSceneMouseEvent* event));

EXTERNC void QWSetupcallbackQKeyEvent(
    void (*f)(int32_t objId, const char *slotName, QKeyEvent* event));

EXTERNC void QWSetupcallbackQMouseEvent(
    void (*f)(int32_t objId, const char *slotName, QMouseEvent* event));

EXTERNC void QWSetupcallbackQObjectQEventReturnsBool(
    bool (*f)(int32_t objId, const char *slotName, QObject* watched, QEvent* event));

EXTERNC void QWSetupcallbackQPaintEvent(
    void (*f)(int32_t objId, const char *slotName, QPaintEvent* event));

EXTERNC void QWSetupcallbackQPainterQRectF(
    void (*f)(int32_t objId, const char *slotName, QPainter* painter, const QRectF& rect));

EXTERNC void QWSetupcallbackQPointFReturnsBool(
    bool (*f)(int32_t objId, const char *slotName, const QPointF& point));

EXTERNC void QWSetupcallbackQResizeEvent(
    void (*f)(int32_t objId, const char *slotName, QResizeEvent* event));

EXTERNC void QWSetupcallbackQTimerEvent(
    void (*f)(int32_t objId, const char *slotName, QTimerEvent* event));

EXTERNC void QWSetupcallbackReturnsBool(
    bool (*f)(int32_t objId, const char *slotName));



EXTERNC void QWSetupSlotCallbackComplexSig(
    void (*f)(int32_t objId, char *slotName, uint32_t dataId));


/////////////////////////////////////////////

EXTERNC void QWDump();

/////////////////////////////////////////////

EXTERNC void QWvalidateEvent(void *obj, int32_t objId, char *methodName);



