
// 
// This file has been automatically generated by RaQt_maker V0.0.5.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include "QVBoxLayout.h"

void * QWQVBoxLayoutCtor_1()
{
    QVBoxLayout * ptr = new QVBoxLayout();
    return reinterpret_cast<void *>(ptr);
}

void QWQVBoxLayoutDtor(void * obj)
{
    QVBoxLayout * ptr = reinterpret_cast<QVBoxLayout *>(obj);
    delete ptr;
}

