
// 
// This file has been automatically generated by RaQt_maker V0.0.6.
// To modify and regenerate it, see the source code available here: 
//         https://github.com/yguillemot/RaQt_maker
// 

#include <stdint.h>
#include <QtWidgets>
#include "externc.h"

EXTERNC void * QWQWidgetCtor(void * parent, int  f);
EXTERNC void * SCWQWidgetCtor(void * parent, int  f);
EXTERNC void QWQWidgetsetDisabled(void * obj, int8_t  arg1);
EXTERNC int32_t QWQWidgetwidth(void * obj);
EXTERNC int32_t QWQWidgetheight(void * obj);
EXTERNC void QWQWidgetsetMinimumSize_2(void * obj, int32_t  minw, int32_t  minh);
EXTERNC void QWQWidgetsetMaximumSize_2(void * obj, int32_t  maxw, int32_t  maxh);
EXTERNC void QWQWidgetsetMinimumWidth(void * obj, int32_t  minw);
EXTERNC void QWQWidgetsetMinimumHeight(void * obj, int32_t  minh);
EXTERNC void QWQWidgetsetMaximumWidth(void * obj, int32_t  maxw);
EXTERNC void QWQWidgetsetMaximumHeight(void * obj, int32_t  maxh);
EXTERNC void QWQWidgetsetFixedSize_2(void * obj, int32_t  w, int32_t  h);
EXTERNC void QWQWidgetsetFixedWidth(void * obj, int32_t  w);
EXTERNC void QWQWidgetsetFixedHeight(void * obj, int32_t  h);
EXTERNC void * QWQWidgetmapToGlobal(void * obj, void * arg1);
EXTERNC void * QWQWidgetmapFromGlobal(void * obj, void * arg1);
EXTERNC void * QWQWidgetmapToParent(void * obj, void * arg1);
EXTERNC void * QWQWidgetmapFromParent(void * obj, void * arg1);
EXTERNC void * QWQWidgetmapTo(void * obj, void * arg1, void * arg2);
EXTERNC void * QWQWidgetmapFrom(void * obj, void * arg1, void * arg2);
EXTERNC void * QWQWidgetfont(void * obj);
EXTERNC void QWQWidgetsetFont(void * obj, void * arg1);
EXTERNC void QWQWidgetsetMouseTracking(void * obj, int8_t  enable);
EXTERNC int8_t QWQWidgethasMouseTracking(void * obj);
EXTERNC void QWQWidgetrender_1(void * obj, void * target, void * targetOffset, void * sourceRegion, int  renderFlags);
EXTERNC void QWQWidgetsetWindowTitle(void * obj, char * arg1);
EXTERNC void QWQWidgetsetToolTip(void * obj, char * arg1);
EXTERNC int8_t QWQWidgetisActiveWindow(void * obj);
EXTERNC void QWQWidgetactivateWindow(void * obj);
EXTERNC void QWQWidgetupdate_1(void * obj);
EXTERNC void QWQWidgetrepaint_1(void * obj);
EXTERNC void QWQWidgetupdate_2(void * obj, int32_t  x, int32_t  y, int32_t  w, int32_t  h);
EXTERNC void QWQWidgetrepaint_2(void * obj, int32_t  x, int32_t  y, int32_t  w, int32_t  h);
EXTERNC void QWQWidgetshow(void * obj);
EXTERNC void QWQWidgethide(void * obj);
EXTERNC void QWQWidgetsetSizePolicy_2(void * obj, int  horizontal, int  vertical);
EXTERNC int32_t QWQWidgetheightForWidth(void * obj, int32_t  arg1);
EXTERNC int8_t QWQWidgethasHeightForWidth(void * obj);
EXTERNC void * QWQWidgetcontentsRect(void * obj);
EXTERNC void QWQWidgetsetLayout(void * obj, void * arg1);
EXTERNC void QWvalidateCB_QWidget(void *obj, int32_t objId, char *methodName);
EXTERNC void QWQWidgetDtor(void *);
EXTERNC void SCWQWidgetDtor(void *);
